### ISSUE TITLE
[FEATURE] Connect and Disconnect commands

### ISSUE THREAD

**Issue by dolphin-cat** [3arthqu4ke/HMC-Specifics#2]
where are connect and disconnect commands? yes ik i can use gui, click and text commands

**Comment by 3arthqu4ke** [comment]
They have not been implemented due to laziness... Yes you can use Gui, Click and Text.
You can also specify a server to join on launch: https://github.com/3arthqu4ke/HeadlessMc/issues/8#issuecomment-1159464185
if that helps.

**Comment by dolphin-cat** [comment]
i noticed that and i am trying to implement them myself but i am unable to figure out how

**Comment by dolphin-cat** [comment]
> You can also specify a server to join on launch

i have to edit the configuration file, i can't just do hmc launch profile -args "--server 1.1.1.1" or something similar

**Comment by dolphin-cat** [comment]
although i think implementing a --server is simpler than a connect command

**Comment by 3arthqu4ke** [comment]
Now available in 1.19.3 and 1.12.2 and future releases. Might backport to other versions.
