### ISSUE TITLE
Any way to move the player?

### ISSUE THREAD

**Issue by louiscav** [3arthqu4ke/HMC-Specifics#3]
Is there any way to move the player with keyboard inputs? (basic keys like w,a,s,d)

**Comment by 3arthqu4ke** [comment]
No, but you could install baritone and then use a command like `msg "goto x y z"`

**Comment by louiscav** [comment]
Sweat, thanks for answering. Any chance you know a way to control the mouse and clicks?

**Comment by 3arthqu4ke** [comment]
Controlling clicks is possible in open menus via the click, text and gui commands. For looking around and placing blocks sadly not.

**Comment by louiscav** [comment]
Ok, thanks a lot
