### ISSUE TITLE
HeadlessMc crashes when using the mod on forge 1.12.2

### ISSUE THREAD

**Issue by Overrage14** [3arthqu4ke/HMC-Specifics#4]
HeadlessMc crashes before minecraft even opens a window.

I'm using command `launch 1 -id -commands` where id 1 is 1.12.2-forge-14.23.5.2860

Here's my latest.log file:
[latest.log](https://github.com/3arthqu4ke/HMC-Specifics/files/9898726/latest.log)

**Comment by 3arthqu4ke** [comment]
You do not need the -commands flag when you use the HMC-Specifics.

**Comment by Overrage14** [comment]
Ok thank you
