### ISSUE TITLE
Cannot put a space using the MSG action

### ISSUE THREAD

**Issue by Gonzu2** [3arthqu4ke/HMC-Specifics#6]
Trying to do <msg /mine reset>
Outputs - "MessageCommand received multiple arguments. If you want to send a message containing spaces escape them using "."

**Comment by Gonzu2** [comment]
I should read the errors to the end, apologies :D I feel stupid 🤦

**Comment by Gonzu2** [comment]
Okay I don't understand how to do it, I tried doing msg /mine "reset but it doesn't work either. Could you give me an example?

**Comment by 3arthqu4ke** [comment]
I think it should be `msg "/mine reset"

**Comment by Gonzu2** [comment]
Ahhh gotcha, thanks for the help :)
