### ISSUE TITLE
no main manifest attribute, in hmc-specifics-fabric-1.20.1-1.2.2.jar

### ISSUE THREAD

**Issue by RaisingAgent** [3arthqu4ke/HMC-Specifics#8]
`java -jar hmc-specifics-fabric-1.20.1-1.2.2.jar`

Error: `no main manifest attribute, in hmc-specifics-fabric-1.20.1-1.2.2.jar`

using openjdk version "1.8.0_382"

**Comment by 3arthqu4ke** [comment]
The hmc-specifics are mods. You place the jar in your mods folder.
