### ISSUE TITLE
[REQUEST] Full mod for newer minecraft versions

### ISSUE THREAD

**Issue by krashy-i386** [3arthqu4ke/HMC-Specifics#9]
Will the full mod with proxy capability release for newer minecraft versions?

**Comment by 3arthqu4ke** [comment]
Sorry, I am not sure what you mean. The HMC-Specifics already released for the latest Minecraft version (1.20.1). If you mean [HeadlessMc](https://github.com/3arthqu4ke/HeadlessMc), it is not a mod but a launcher which can launch any of the newer minecraft versions.

**Comment by krashy-i386** [comment]
My bad, i totally fumbled the repositories when creating the issue. But in short after following the tutorial on the earthhack to setup HeadlessMc, the proxy doesnt seem to work (1.19.4). But i already managed to find another solution so thx anyway :)
